"""MongoDB collection name constants."""

CAMPAIGN_SESSIONS = "campaign_sessions"
RESEARCH_FINDINGS = "research_findings"
CONTENT_VARIANTS = "content_variants"
DEPLOYMENT_RECORDS = "deployment_records"
FEEDBACK_EVENTS = "feedback_events"
INTELLIGENCE_ENTRIES = "intelligence_entries"
CYCLE_RECORDS = "cycle_records"
TOOL_CACHE = "tool_cache"
QUARANTINE = "quarantine_events"
DEAD_LETTER_QUEUE = "dead_letter_queue"
SEGMENTS = "segments"
PROSPECT_CARDS = "prospect_cards"
MCP_SERVERS = "mcp_servers"
